# -*- coding: utf-8 -*-
"""Decorator Pertemuan 13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P87JkYwP50W2KJd2bWjbRl9zlwyLk5tc

CREATE DECORATOR
"""

def lowercase(func):
  def wrapper():
    func_ret = func()
    change_to_lowercase = func_ret.lower()
    return change_to_lowercase
  return wrapper

"""Testing 1"""

def hello_function():
  return 'HELLO WORD'

decorate = lowercase(hello_function)
print(decorate())

"""Testing 2"""

@lowercase
def hello_function():
  return 'HELLO WORLD'

print(hello_function())

def hello_function():
  return 'HELLO WORLD'

print(hello_function())

"""MULTIPLE DECORATORS"""

def split_sentence(func):
  def wrapper():
    func_ret = func()
    output = func_ret.split()
    return output
  return wrapper@split-sentence